### ISSUE TITLE
Implementing arbitrary computation on the intersection

### ISSUE THREAD

**Issue by zaczanussi** [shahakash28/2PC-Circuit-PSI#2]
In the PoPets paper, it is mentioned how one might extend the protocol in this library to support payloads from both parties. These payloads could then be input into a circuit that computes PSI on the labels followed by some arbitrary computation on the payloads.

Some colleagues and I are investigating the possibility of extending this library to perform this functionality. The computations in question are summary statistics. For example, the Sender is a credit card company with labels that are the values of transactions, and the Receiver has both qualitative and numerical labels on each of the respondents. We would like to compute aggregates of the transactions based on the qualities of respondents.

I was wondering if you had any thoughts on how one could go about adapting this code to add this functionality? How much work do you think it would take? If we went ahead with implementing this, I'm sure we could submit a pull request, if desired. As far as I can see, payloads is not currently implemented here. Is there a version of your code where it is? 

Thanks!

**Comment by shahakash28** [comment]
Thanks for reaching out! Appendix D of our paper discusses the protocol in fair detail that can help with implementation. One needs to reuse hashtables constructed previously for input elements and then duplicate the steps to construct "hint" corresponding to payloads. 

I think 2 days of coding effort should suffice. Yes, we haven't implemented it yet.
