### ISSUE TITLE
Processes hang with Docker

### ISSUE THREAD

**Issue by jimouris** [shahakash28/2PC-Circuit-PSI#3]
Hello,

I'm trying to run an example using Docker but the processes seem to hang. 

After I built with docker, I'm running the following from two different terminals:
```
docker start cpsi
docker exec -it cpsi bash
```

Terminal 1:
```
root@25674f2f5f31:/2PC-Circuit-PSI/build# bin/gcf_psi -r 0 -p 31000 -n 100 -b 58 -m 5 -y PSM2

^C
```

Terminal 2:
```
root@25674f2f5f31:/2PC-Circuit-PSI/build# bin/gcf_psi -r 1 -a localhost -p 31000 -n 65536 -b 58 -m 5 -y PSM2


^C
```

Am I doing something wrong? 

Thanks!!

**Comment by shahakash28** [comment]
Hi!
Replace localhost with 0.0.0.0 and see if it works.

**Comment by jimouris** [comment]
It does, thanks!
